config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "users#index"
  get "/", to: "users#index"
  post "/users", to: "users#create"
  post "/sessions", to: "sessions#create"
  get "/dashboard", to: "home#index"
  get "/admin", to: "home#admin"
  get "/logout", to: "sessions#destroy"
  post "/update", to: "sessions#update"
  get "/data", to: "home#data"
  get "/subpage", to: "home#subpage"
  get "/seo", to: "home#seo"
  get "/listpage", to: "home#listpage"
  get "/pagedata", to: "home#pagedata"
  post "/home", to: "home#create"
  get "/edit", to: "home#edit"
  post "/subpage", to: "home#createsubpage"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subpage.rb
class Subpage < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image
end

app/models/userdatum.rb
class Userdatum < ApplicationRecord
end

app/models/userpage.rb
class Userpage < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout"user"
    def index
       
        @user = User.find(session[:user_id])
        @pages = Userpage.where(userid: session[:user_id])
    end

    def edit
       
        @user = User.find(session[:user_id])
        @pages = Userpage.where(userid: session[:user_id])
    end

    def admin
        @alluser = User.all
        @user = User.find(session[:user_id])
    end

    def data
       @userid=session[:user_id] 
    end

    def pagedata
        @pages=Userpage.where(id: params[:pageid]) 
     end

    def seo
        @pages = Userpage.where(userid: session[:user_id])
    end

    def listpage
        @pages = Userpage.where(userid: session[:user_id])
        
    end

    def subpage
        @pages=Userpage.where(id: params[:pageid]) 
    end

    def create
        page = Userpage.new(page_params)
        if page.save
            
            redirect_to '/dashboard'
        else
            flash[:register_errors] = user.errors.full_messages
            redirect_to '/'
        end
        # user = User.create!(user_params)
        # session[:user_id] = user.id
        # redirect_to '/dashboard'
    end

    def createsubpage
        page = Subpage.new(subpage_params)
        if page.save
            
            redirect_to '/listpage'
        else
            flash[:register_errors] = user.errors.full_messages
            redirect_to '/'
        end
        # user = User.create!(user_params)
        # session[:user_id] = user.id
        # redirect_to '/dashboard'
    end

    private
        def page_params
            params.require(:page).permit(:userid, :title, :pagetitle, :keywords, :metadescription, :description, :image)

        end
    
    private
        def subpage_params
            params.require(:page).permit(:pageid, :title, :pagetitle, :keywords, :metadescription, :description, :image)

        end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            #send email
            PasswordMailer.with(user: @user).reset.deliver_now
        end

        redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to "/", alert: "Your token has expired. Please try again"
    end  
    
    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to "/", notice: "Your password was reset successfully> Please sign in"
        else
            render :edit
        end
    end
    
    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        user = User.find_by(email:login_params[:email])
        if user && user.authenticate(login_params[:password])
            if user.isadmin
                session[:user_id] = user.id
                redirect_to '/admin'
            else
                session[:user_id] = user.id
                redirect_to '/dashboard'
            end
        else
            flash[:login_errors] = ['invalid credentials']
            flash.now[:alert] = 'User not found!'
            
            # flash[:alert] = "User not found."
            # redirect_to '/'
        end
    end

    def update
        user = User.find(session[:user_id])
        if user.update(user_params)
            redirect_to '/dashboard'
        else
            flash[:login_errors] = ['invalid credentials']
            redirect_to '/dashboard'
        end
    end

    

    def destroy
        session[:user_id] = nil
        redirect_to '/', notice: "Logged out!"
    end

    private
        def login_params
            params.require(:login).permit(:email, :password)
        end

    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone, :profession, :image)

        end

        

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
    end

    def create
        user = User.new(user_params)
        if user.save
            session[:user_id] = user.id
            redirect_to '/dashboard'
        else
            flash[:register_errors] = user.errors.full_messages
            redirect_to '/'
        end
        # user = User.create!(user_params)
        # session[:user_id] = user.id
        # redirect_to '/dashboard'
    end

    

    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone, :profession, :image, :isadmin)

        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/data.html.erb
<!DOCTYPE html>
<html>
<body>
<div style="border: 1px solid #ccc;
box-shadow: 3px 3px 2px #ccc;
transition: 0.5s; padding: 5%; padding-top: 0%; width: 80%; margin-top: 5%; margin-left: 10%; background-color: white; color: rgb(33, 135, 231)">
<h2 style="text-align: center">Create Your Own Page</h2>


<form action="/home" enctype="multipart/form-data" method = "POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="title"><b>Title:</b></label><br>
  <input type="text" id="title" name="page[title]" value=""><br>
  <label for="page title"><b>Page Title:</b></label><br>
  <input type="text" id="pagetitle" name="page[pagetitle]" value=""><br>
  <label for="keywords"><b>Keywords:</b></label><br>
  <input type="text" id="keywords" name="page[keywords]" value=""><br>
  <label for="meta description"><b>Meta description:</b></label><br>
  <input type="text" id="metadescription" name="page[metadescription]" value=""><br>
  <label for="description" ><b>Description</b></label><br>
  <textarea type="text" id="description" rows="10" cols="110" name="page[description]" value=""></textarea><br><br>
  <label for="image"><b>Image:</b></label><br>
  <input type="file" id="user_image" class="form-control" name="page[image]" placeholder="Password *" value="" />
  <input type="hidden" id="title" name="page[userid]" value=<%= @userid %>><br>
  </br>
  <input type="submit" value="Submit">
  <button style="width: 8%; height: 8%; float: right; color: blue; border: none"><a style = " color: blue" id = "link" href="/subpage"><img style="width: 100%; height: 100%" src="https://www.kindpng.com/picc/m/543-5432090_transparent-addition-symbol-clipart-icon-button-add-png.png"></a></button>
</form> 

</div>

</body>
</html>

app/views/home/edit.html.erb
<div class="container emp-profile">
    <div class="row">
        <div class="col-md-4">
            <div class="profile-img">
                <% if @user.image.attached? %>
                    <%= link_to image_tag(@user.image), users_path %>
                <% else %>
                    <img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="Avatar" class="avatar">
                    <h6> (To add your photo go to edit profiles) </h6>
                <% end %>
            </div>                
        </div>
        <div class="col-md-6">
            <div class="profile-head">
                <h5>
                    <%= @user.name %>
                </h5>
                <h6>
                    <%= @user.profession %>
                </h6>
                <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="profile-work">
                                                                                                                                        <p>WORK LINK</p>
                                                                                                                                        <a href="">Website Link</a><br/>
                                                                                                                                        <a href="">Bootsnipp Profile</a><br/>
                                                                                                                                        <a href="">Bootply Profile</a>
                                                                                                                                        <p>SKILLS</p>
                                                                                                                                        <a href="">Web Designer</a><br/>
                                                                                                                                        <a href="">Web Developer</a><br/>
                                                                                                                                        <a href="">WordPress</a><br/>
                                                                                                                                        <a href="">WooCommerce</a><br/>
                                                                                                                                        <a href="">PHP, .Net</a><br/>
                                                                                                    </div>
                </div>                  
                <div class="col-md-8">
                    <div class="tab-content profile-tab" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        
                                <form id = "editable"  enctype="multipart/form-data"  action="/update" method = "POST">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>User Id</label>
                                        </div>
                                        <div class="col-md-6">
                                        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
                                            <p><%= @user.id %></p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Name</label>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" id="name" name="user[name]" autofocus value=<%= @user.name %> >
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Email</label>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" id="email" name="user[email]" value=<%= @user.email %> >
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Phone</label>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" pattern="[789][0-9]{9}"  id="phone" name="user[phone]" value=<%= @user.phone %> >
                                            <small>Format: 10 digit Mobile Number</small>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Profession</label>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" id="profession" name="user[profession]" value=<%= @user.profession %> >
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Change image</label>
                                        </div>
                                        <div class="col-md-6">
                                        <input type="file" id="user_image" class="form-control" name="user[image]" placeholder="Password *" value="" />
                                        </div>
                                    </div>
                                    </br>
                                    <button  id = "can" onclick="cancel(); event.preventDefault();">Cancel</button>
                                    <button type = "submit"  id = "sub">Submit</button>
                                </form>
                            
                                

                                
                        </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Experience</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>Expert</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Hourly Rate</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>10$/hr</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Total Projects</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>230</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>English Level</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>Expert</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Availability</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>6 months</p>
                                        </div>
                                    </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label>Your Bio</label><br/>
                                    <p>Your detail description</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        
    </div>

app/views/home/listpage.html.erb
<!DOCTYPE html>
<html>
<body>
<div style="border: 1px solid #ccc;
box-shadow: 3px 3px 2px #ccc;
transition: 0.5s; padding: 5%; padding-top: 0%; width: 80%; margin-top: 5%; margin-left: 10%; background-color: white;">
<h2 style="text-align: center; color: rgb(33, 135, 231)">List Page</h2>
<table class="table table-striped custab" style="color: blue; width: 100%;  ">
<thead>
<tr>
<th style="width: 40%; color:rgb(33, 135, 231)">Page Title</th>
<th style="width: 30%; color:rgb(33, 135, 231)">Add subpages</th>

</tr>
</thead>
<tbody>
<% @pages.each do |page| %>
    <tr>
        
        <td >
        <a href="/pagedata?pageid=<%= page.id %>&keywords=<%= page.keywords %>&metadata=<%= page.metadescription %>"><%= page.title %></a>
        </td>
        <td>
        <button><a style = " color: blue" id = "link" href="/subpage?pageid=<%= page.id %>">Add</a></button>
        </td>
        <td>

        
       
    </tr>
    <% end %>
    </tbody>
    </table>
    </div>
    </body>
    </html>

app/views/home/pagedata.html.erb
<!DOCTYPE html>
<html>
<body>
<% @pages.each do |page| %>
<div style="border: 1px solid #ccc;
box-shadow: 3px 3px 2px #ccc;
transition: 0.5s; padding: 5%; color: rgb(33, 135, 231); padding-top: 0%; width: 80%; margin-top: 5%; margin-left: 10%; background-color: white;">
<h2 style="text-align: center; color: rgb(33, 135, 231)"><%= page.title %></h2>
<h3 style="text-align: center; color: rgb(33, 135, 231)"><%= page.pagetitle %></h3></br></br>
<p float= "left" style="color: rgb(33, 135, 231)"><b>Keywords: </b><%= page.keywords %></p></br>
<h4><b>Meta Description</b></h4>
<p style="color: rgb(33, 135, 231)"><%= page.metadescription %></p></br>
<p><%= page.description %></p></br>
    <%= link_to image_tag(page.image, style: 'width: 100%')%>

    </div>
    <% end %>
    </body>
    </html>

app/views/home/seo.html.erb
<!DOCTYPE html>
<html>
<body>
<div style="border: 1px solid #ccc;
box-shadow: 3px 3px 2px #ccc;
transition: 0.5s; padding: 5%; padding-top: 0%; width: 80%; margin-top: 5%; margin-left: 10%; background-color: white;">
<h2 style="text-align: center; color: rgb(33, 135, 231)">SEO Page</h2>
<table class="table table-striped custab" style="color: blue; width: 100%;  ">
<thead>
<tr>
<th style="width: 40%; color:rgb(33, 135, 231)">MetaDescription</th>
<th style="width: 30%; color:rgb(33, 135, 231)">Kewords</th>
<th style="width: 30%; color:rgb(33, 135, 231)">URL</th>
</tr>
</thead>
<tbody>
<% @pages.each do |page| %>
    <tr>
        
        <td >
        <%= page.metadescription %>
        </td>
        <td>
        <%= page.keywords %>
        </td>
        <td>
        <a href="/pagedata?pageid=<%= page.id %>&keywords=<%= page.keywords %>&metadata=<%= page.metadescription %>">http://localhost:3000/pagedata?pageid=<%= page.id %>&keywords?<%= page.keywords %>&page_id=<%= page.id %></a>
        </td>
        
       
    </tr>
    <% end %>
    </tbody>
    </table>
    </div>
</body>
</html>

app/views/home/subpage.html.erb
<!DOCTYPE html>
<html>
<body>

<div style="padding: 5%; padding-top: 0%; width: 80%; border: double black; margin-left: 10%; background-color: white;">
<h2 style="text-align: center">Create SubPage</h2>
<% @pages.each do |page| %>
<form action="/subpage" enctype="multipart/form-data" method = "POST">
  

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="title"><b>Title:</b></label><br>
  <input type="text" id="title" name="page[title]" value=""><br>
  <label for="page title"><b>Page Title:</b></label><br>
  <input type="text" id="pagetitle" name="page[pagetitle]" value=""><br>
  <label for="keywords"><b>Keywords:</b></label><br>
  <input type="text" id="keywords" name="page[keywords]" value=""><br>
  <label for="meta description"><b>Meta description:</b></label><br>
  <input type="text" id="metadescription" name="page[metadescription]" value=""><br>
  <label for="description" ><b>Description</b></label><br>
  <textarea type="text" id="description" rows="10" cols="110" name="page[description]" value=""></textarea><br><br>
  <label for="image"><b>Image:</b></label><br>
  <input type="file" id="user_image" class="form-control" name="page[image]" placeholder="Password *" value="" />
  <input type="hidden" id="title" name="page[userid]" value=<%= @userid %>><br>
  </br>
  <input type="submit" value="Submit">
  <button style="width: 8%; height: 8%; float: right; color: blue; border: none"><a style = " color: blue" id = "link" href="/subpage"><img style="width: 100%; height: 100%" src="https://www.kindpng.com/picc/m/543-5432090_transparent-addition-symbol-clipart-icon-button-add-png.png"></a></button>
</form> 
<% end %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>



<!------ Include the above in your HEAD tag ---------->


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/menu" %>
  <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>
    
    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-controller", placeholder: "sleve@apple.com" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/users/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<script type = "text/javascript">     
    event.preventDefault();
</script>
<div class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
            <h3>Welcome</h3>
            <p>This is my first Ruby on Rails App!</p>
        </div>
        <div class="col-md-9 register-right">
        <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Sign Up</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Sign In</a>
        </li>
    </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="register-heading">Registration</h3>
                    <form action="/users" enctype="multipart/form-data" method = "POST" class="row register-form">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
                                <input type="text" class="form-control" name="user[name]" placeholder="Your Full Name *" required value="" />
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="user[profession]" placeholder="Your Profession *" required value="" />
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="user[password]" placeholder="Password *" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required value="" />
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="email" class="form-control" name="user[email]" placeholder="Your Email *" size="30" required value="" />
                            </div></br>
                            <div class="form-group">
                                <input type="text" minlength="10" maxlength="10" name="user[phone]"  class="form-control" placeholder="Your Phone *" required value="" />
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="user[password_confirmation]" placeholder="Confirm Password *" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required value="" />
                            </div>
                            <input type="submit" class="btnRegister"  value="Register"/>
                        </div>
                    </form>
                </div>
                <div class="tab-pane fade show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <h3  class="register-heading">Sign In</h3>
                    <form action="/sessions" method = "POST" class="row register-form">
                        <div class="col-md-12">
                            <div class="form-group">
                                <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
                                <input type="email" class="form-control" placeholder="Email *" size="30" name="login[email]" required value="" />
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Password *" name="login[password]" required value="" />
                                
                            </div>

                            <div>
                                <a href="/password/reset">Forgot your password?</a>
                                <% link_to "Forgot your password?", password_reset_path %>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btnRegister"  value="Sign In"/>
                            </div>
                            <% if flash[:login_errors] %>
                                <% flash[:login_errors].each do | error| %>
                                    <p><%=error %>
                                    <p>
                                    <% end %>
                            <% end %>
                            
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>